### ISSUE TITLE
SC 3.9 is going to break SynthDef v1 compatibility

### ISSUE THREAD

**Issue by Sciss** [Sciss/ScalaCollider#80]
This is a shitty decision which means again that we have to assume which SC version the user is running: https://github.com/supercollider/supercollider/issues/3266

The best might be to add an `serverVersion` field to the server configuration, putting the responsibility on the user, perhaps filling it in from `Server.version`.

The default v1 of `SynthDef:write` should then change to v2 __if__ this version works with current stable 3.8.

**Comment by brianlheim** [comment]
Hey, could you please confirm this? There is no real evidence AFAICT that this is the case. Farther down the thread I note that the file we were testing is marked as v2.

**Comment by Sciss** [comment]
@brianlheim So you mean v1 should in principle be still supported? I'll do a test then the next days.

**Comment by brianlheim** [comment]
Yes, it should still be supported. We don't have enough info to say that it's broken or even risky at this point. Sorry for the confusion. I will also do some testing myself.

**Comment by brianlheim** [comment]
OK, I just made a synthdef in v1 format from within SuperCollider and for me, it runs fine on the server (scsynth). If you find something that breaks it, please file an issue and we'll take a look at it!

**Comment by brianlheim** [comment]
@Sciss - there was in fact an issue! https://github.com/supercollider/supercollider/pull/3382 (included in the next release candidate for 3.9) fixes it.

**Comment by brianlheim** [comment]
But, please do test if you have the time. We're planning to release next week.

**Comment by Sciss** [comment]
I'm running 3.9.1 since a while, no issues. Closing
